default:
  extensions:
    Behat\MinkExtension\Extension:
      base_url:  'http://newtree/'
      goutte:    ~

default:
  extensions:
    Behat\MinkExtension\Extension:
      base_url:  'http://newtree-de/'
      goutte:    ~
