propel:
  database:
      connections:
          default:
              adapter: mysql
              dsn: "mysql:host=localhost;dbname=DE_development_zed"
              user: development
              password: mate20mg
              settings:
                  charset: utf8
                  queries:
                      utf8: "SET NAMES utf8 COLLATE utf8_unicode_ci, COLLATION_CONNECTION = utf8_unicode_ci, COLLATION_DATABASE = utf8_unicode_ci, COLLATION_SERVER = utf8_unicode_ci"
          zed:
              adapter: mysql
              classname: Propel\Runtime\Connection\ConnectionWrapper
              dsn: "mysql:host=localhost;dbname=DE_development_zed"
              user: development
              password: mate20mg
              attributes:
  runtime:
      defaultConnection: zed
      connections:
          - zed
  generator:
      defaultConnection: zed
      connections:
          - zed

  paths:
      phpDir: /data/shop/development/current
      propelGenDir: %phpDir%/src/Generated/Propel
      sqlDir: %propelGenDir%/Sql
      migrationDir: %propelGenDir%/Migration
      phpConfDir: %propelGenDir%/Config
      schemaDir: %propelGenDir%/Schema
