build:
    environment:
        php: '7.1'
    dependencies:
        before:
            - 'composer remove --dev spryker/git-hook phpstan/phpstan'

    tests:
        override:
            - true # disable test execution on scrutinizer

build_failure_conditions:
    - 'project.metric("scrutinizer.quality", < 9.57)'
