language: php
php:
#- '5.5'
- '5.6'
#- '7.0'

addons:
  postgresql: "9.4"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - postgresql
  - redis

sudo: false

env:
  global:
    - APPLICATION_ENV=development
    - APPLICATION_STORE=DE

install:
  - composer self-update && composer --version
  - composer install --no-interaction

before_script:
  - mv config/Zed/propel.ci.yml config/Zed/propel.yml
  - cp config/Shared/config_default-development.ci.php config/Shared/config_default-development_DE.php
  - cp config/Shared/config_default-development.ci.php config/Shared/config_default-test.php

script:
  - vendor/bin/console propel:install -o
  - vendor/bin/console transfer:generate
  - vendor/bin/console setup:init-db
  - vendor/bin/console setup:search
  - vendor/bin/console import:demo-data

  - vendor/bin/console application:build-navigation-cache

  - vendor/bin/codecept run --debug -x Acceptance

  - vendor/bin/console collector:storage:export
  - vendor/bin/console collector:search:export

  - vendor/bin/console code:sniff

notifications:
  email: false

sudo: required
