language: php
php:
  - 5.6
  - 7.0
matrix:
  allow_failures:
    - env: TEST_GROUP=acceptance

addons:
  postgresql: 9.4
  apt:
    packages:
      - graphviz

  hosts:
    - zed.de.spryker.test
    - www.de.spryker.test

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - postgresql
  - elasticsearch
  - redis

sudo: required

env:
  global:
    - APPLICATION_ENV=test
    - APPLICATION_STORE=DE
  matrix:
    - TEST_GROUP=without-acceptance
    - TEST_GROUP=acceptance

install:
  - composer self-update && composer --version
  - composer install --no-interaction

before_script:
  - mkdir -p shared/data/common/jenkins
  - mkdir -p shared/data/common/jenkins/jobs
  - mv config/Zed/propel.ci.yml config/Zed/propel.yml
  - cp config/Shared/config_default-test.ci.php config/Shared/config_default-test.php

  - mkdir -p data/DE/cache/Yves/twig -m 0777
  - mkdir -p data/DE/cache/Zed/twig -m 0777
  - mkdir -p data/DE/logs -m 0777

    # install apache with fastcgi modules
  - sudo apt-get install apache2 libapache2-mod-fastcgi

    # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "session.save_path = '/tmp'" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

    # configure apache virtual hosts
  - sudo cp -f config/Shared/ci/travis/php5-fpm.conf /etc/apache2/conf.d/php5-fpm.conf
  - sudo cp -f config/Shared/ci/travis/travis-ci-apache-yves /etc/apache2/sites-available/yves
  - sudo cp -f config/Shared/ci/travis/travis-ci-apache-zed /etc/apache2/sites-available/zed
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/yves
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/zed
  - sudo ln -s /etc/apache2/sites-available/yves /etc/apache2/sites-enabled/yves
  - sudo ln -s /etc/apache2/sites-available/zed /etc/apache2/sites-enabled/zed
  - sudo service apache2 restart

   #Install antelope
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install npm -g
  - sudo npm install -g antelope
  - sudo antelope install
  - sudo antelope build

script:
  - ./setup_test -b

  - vendor/bin/console transfer:generate
  - vendor/bin/console application:build-navigation-cache

  - chmod -R 777 data/
  #- if [[ $TEST_GROUP == 'without-acceptance' ]]; then vendor/bin/codecept run -x Acceptance ; fi
  #- if [[ $TEST_GROUP == 'acceptance' ]]; then vendor/bin/codecept run -g Acceptance ; fi

  - vendor/bin/codecept run
# Just in case you want to know about errors uncomment this
#  - cat /tmp/zed-error.log

  - vendor/bin/console code:sniff

notifications:
  email: false
