language: php
php:
  - 5.6
  - 7.0
matrix:
  allow_failures:
    - env: TEST_GROUP=acceptance

addons:
  postgresql: 9.4
  apt:
    packages:
      - graphviz

  hosts:
    - zed.de.spryker.test
    - www.de.spryker.test

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - postgresql
  - redis

sudo: required

env:
  global:
    - APPLICATION_ENV=test
    - APPLICATION_STORE=DE
  matrix:
    - TEST_GROUP=without-acceptance
    - TEST_GROUP=acceptance

install:
  - chmod -R a+x deploy/travis/
  - composer self-update && composer --version
  - composer install --no-interaction
  - if [[ $TEST_GROUP == 'acceptance' ]]; then deploy/travis/install_elasticsearch.sh; fi

before_script:
  - mkdir -p shared/data/common/jenkins
  - mkdir -p shared/data/common/jenkins/jobs
  - mkdir -p data/DE/cache/Yves/twig -m 0777
  - mkdir -p data/DE/cache/Zed/twig -m 0777
  - mkdir -p data/DE/logs -m 0777
  - chmod -R 777 data/


  - mv config/Zed/propel.ci.yml config/Zed/propel.yml
  - cp config/Shared/config_default-test.ci.php config/Shared/config_default-test.php
  - cp config/Shared/ci/travis/params.sh deploy/setup/params.sh

  - if [[ $TEST_GROUP == 'acceptance' ]]; then deploy/travis/acceptance_env.sh; fi

  - if [[ $TEST_GROUP == 'acceptance' ]]; then ./setup_test -f; fi
  - if [[ $TEST_GROUP == 'without-acceptance' ]]; then ./setup_test -b; fi

script:
  - if [[ $TEST_GROUP == 'without-acceptance' ]]; then vendor/bin/codecept run -x Acceptance ; fi
  - if [[ $TEST_GROUP == 'acceptance' ]]; then vendor/bin/codecept run -g Acceptance ; fi

  - vendor/bin/phpcs $(pwd) --standard=$(pwd)/vendor/spryker/code-sniffer/Spryker/ruleset.xml --ignore=vendor/

notifications:
  email: false
