language: php
php:
#- '5.5'
- '5.6'
#- '7.0'

addons:
  postgresql: "9.4"
  apt:
    packages:
      - graphviz

  hosts:
    - zed.de.spryker.dev
    - www.de.spryker.dev

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - postgresql
  - elasticsearch
  - redis

sudo: false

env:
  global:
    - APPLICATION_ENV=development
    - APPLICATION_STORE=DE

install:
  - composer self-update && composer --version
  - composer install --no-interaction

before_script:
  - mkdir -p shared/data/common/jenkins
  - mkdir -p shared/data/common/jenkins/jobs
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f config/Shared/ci/travis/travis-ci-apache-default /etc/apache2/sites-available/default
  # zed virtual host
  - sudo cp -f config/Shared/ci/travis/travis-ci-apache-zed /etc/apache2/sites-available/zed
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/zed
  # yves virtual host
  - sudo cp -f config/Shared/ci/travis/travis-ci-apache-yves /etc/apache2/sites-available/yves
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/yves

  - sudo a2ensite zed
  - sudo a2ensite yves

  - sudo a2enmod rewrite
  - sudo service apache2 restart

  - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mv config/Zed/propel.ci.yml config/Zed/propel.yml
  - cp config/Shared/config_default-development.ci.php config/Shared/config_default-development_DE.php
  - cp config/Shared/config_default-development.ci.php config/Shared/config_default-test.php

script:
  - vendor/bin/console propel:install -o
  - vendor/bin/console transfer:generate
  - vendor/bin/console setup:init-db
  - vendor/bin/console setup:search
  - vendor/bin/console import:demo-data

  - vendor/bin/console application:build-navigation-cache

  - vendor/bin/codecept run --debug -x Acceptance

  - vendor/bin/console collector:storage:export
  - vendor/bin/console collector:search:export

  - vendor/bin/console code:sniff

notifications:
  email: false

sudo: required
