security:
#  default:
#    zed: true

  login_check:
    pattern: '^/login_check$'
    anonymous: ~

  secured:
    pattern: '^/checkout'
    form: {login_path: '/login-old', check_path: '/login_check'}
