security:
#  default:
#    zed: true

  unsecured:
    anonymous: true

  login_check:
    pattern: '^/login_check'

  secured:
    pattern: '^/checkout'
    form: {login_path: '/login', check_path: '/login_check'}
