settings:
  logout:
    logout_path: '/logout'

  securityProvider:
    form:
      login_path: '/login'
      check_path: '/login_check'
      failure_path: '/login'
      username_parameter: 'customerLogin[email]'
      password_parameter: 'customerLogin[password]'
      csrf_parameter: 'customerLogin[_token]'
      csrf_provider: form.csrf_provider
      intention: authentication

    remember_me:
      key: 4hRu9345%eb=drn5&jg7?hesp5ยง
      always_remember_me: true
      name: ADD_COOKIE_NAME
      lifetime: 31536000
      # remember_me_parameter
      # httponly:
      # secure:
      # domain:
      # path:

  customerProvider: 'ProjectA\Yves\Customer\Business\Model\Security\CustomerProvider'
  authModel: 'ProjectA\Yves\Customer\Business\Model\Customer'

firewalls:
  secured:
    pattern: '(^/checkout|^/login_check$|^/logout$|^/customer)'

  unsecured:
    pattern : '^/.*'
    anonymous: true
