stages:
  development:
    composer:
      install-composer:
        command: "Spryker\\Command\\Composer\\ComposerInstallCommand"

      install-dependencies:
        command: "php composer.phar install --prefer-dist"

    before:
      stop-jenkins:
        command: "vendor/bin/console setup:jenkins:disable"

      cache-clear:
        command: "vendor/bin/console cache:empty-all"
        groups:
          - cache

    database:
      flush-elastic-search:
        command: "vendor/bin/console search:flush"
        groups:
          - elastic

      flush-redis:
        command: "vendor/bin/console redis:flush"
        groups:
          - redis

      drop-database:
        command: "vendor/bin/console propel:database:drop"
        groups:
          - Propel

#      drop-schema-files:
#        command: "vendor/bin/console propel:drop:migration-files"
#        groups:
#          - Propel

      setup-propel:
        command: "vendor/bin/console propel:install"
        groups:
          - Propel

    generate:
      ide-auto-completion:
        command: "vendor/bin/console dev:ide:generate-auto-completion"

      generate-transfers:
        command: "vendor/bin/console transfer:generate"

      generate-data-builders:
        command: "vendor/bin/console transfer:databuilder:generate"
        groups:
          - testing

    install:
      init-database:
        command: "vendor/bin/console setup:init-db"

      import:
        command: "vendor/bin/console data:import"

      update-product-labels:
        command: "vendor/bin/console product-label:relations:update"

    export:
      search:
        command: "vendor/bin/console collector:search:export -q"
      storage:
        command: "vendor/bin/console collector:storage:export -q"

    frontend:
      npm:
        command: "npm -i"

<<<<<<< HEAD

=======
      restore:
        drop-database:
          command: "vendor/bin/console propel:database:drop"
          groups:
            - propel

        import-database:
          command: "vendor/bin/console propel:database:import ./data/test.backup_new"
          groups:
            - propel
>>>>>>> core-2001 fixed merge conflicts, update spryker.phar
