env:
  APPLICATION_ENV: devtest

sections:
  generate:
    generate-transfers:
      command: "vendor/bin/console transfer:generate"

  database-flush:
    delete-migration-files:
      command: "vendor/bin/console propel:migration:delete"
      stores: true
      groups:
        - propel

  database-migrate:
    propel-config:
      command: "vendor/bin/console propel:config:convert"
      stores: true
      groups:
        - propel

    propel-create:
      command: "vendor/bin/console propel:database:create"
      stores: true
      groups:
        - propel

    propel-postgres-compatibility:
      command: "vendor/bin/console propel:pg-sql-compat"
      stores: true
      groups:
        - propel

    propel-copy-schema:
      command: "vendor/bin/console propel:schema:copy"
      stores: true
      groups:
        - propel

    propel-build:
      command: "vendor/bin/console propel:model:build"
      groups:
        - propel

    propel-diff:
      command: "vendor/bin/console propel:diff"
      stores: true
      groups:
        - propel

    propel-migrate:
      command: "vendor/bin/console propel:migrate"
      stores: true
      groups:
        - propel

    init-database:
      command: "vendor/bin/console setup:init-db"
      stores: true

    setup-search:
      command: "vendor/bin/console setup:search"
      stores: true
      groups:
        - elastic


  demodata:
    import:
      command: "vendor/bin/console data:import"
      stores: true

    update-product-labels:
      command: "vendor/bin/console product-label:relations:update"
      stores: true

    search-collector:
      command: "vendor/bin/console collector:search:export"
      stores: true

    storage-collector:
      command: "vendor/bin/console collector:storage:export"
      stores: true


  frontend:
    install-package-manager:
      command: "vendor/bin/console frontend:install:package-manager"
      groups:
        - project

    dependencies-install:
      command: "vendor/bin/console frontend:project:install-dependencies"
      groups:
        - project

    yves-install-dependencies:
      command: "vendor/bin/console frontend:yves:install-dependencies"
      groups:
        - yves

    yves-build-frontend:
      command: "vendor/bin/console frontend:yves:build"
      groups:
        - yves

    zed-install-dependencies:
      command: "vendor/bin/console frontend:zed:install-dependencies"
      groups:
        - zed

    zed-build-frontend:
      command: "vendor/bin/console frontend:zed:build"
      groups:
        - zed
